services:
    openzaak:
        image: openzaak/open-zaak:1.12.4
        container_name: openzaak
        platform: linux/amd64
        environment:
            - DB_HOST=openzaak-database
            - DB_POST=5433
            - SECRET_KEY=veryRestrictedSecretKey
            - DB_USER=openzaak
            - DB_PASSWORD=openzaak
            - DB_NAME=openzaak
            - CACHE_DEFAULT=redis:6379/0
            - CACHE_AXES=redis:6379/0
            - DEBUG=true
            - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
            - OPENZAAK_SUPERUSER_USERNAME=admin
            - OPENZAAK_SUPERUSER_EMAIL=admin@admin.org
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - DJANGO_SUPERUSER_PASSWORD=admin
            - SENDFILE_BACKEND=django_sendfile.backends.simple
        ports:
            - "8001:8000"
        depends_on:
            - openzaak-database
            - redis

    openzaak-database:
        image: mdillon/postgis:11
        container_name: openzaak-database
        platform: linux/amd64
        ports:
            - "8091:5432"
        environment:
            - POSTGRES_USER=openzaak
            - POSTGRES_PASSWORD=openzaak
            - POSTGRES_DB=openzaak
        volumes:
            - ./imports/open-zaak:/docker-entrypoint-initdb.d
    redis:
        image: redis:6.2.6
        container_name: redis

    haalcentraal-personen:
        container_name: haalcentraal-personen
        image: ghcr.io/brp-api/personen-mock:2.2.1
        platform: linux/amd64
        environment:
            - ASPNETCORE_ENVIRONMENT=Release
            - ASPNETCORE_URLS=http://+:5010
        ports:
            - "5010:5010"
        networks:
            - brp-api-network

networks:
    brp-api-network:
        name: brp-api-network
