spring:
  application:
    name: panorama

server:
  port: 8085

logging:
  level:
    root: INFO
    org:
      springframework:
        security:
          web:
            authentication: INFO

panorama:
  config:
    authorization:
      clients:
        - client-id: gzac
          api-key:
          roles:
            - HAALCENTRAAL_BRP_GET_PERSOON
            - HAALCENTRAAL_BRP_GET_PERSONEN
            - ZAKEN_API_GET_ZAKEN
    modules:
      haalcentraal-brp:
        enabled: true
        properties:
          api-url:
          api-key:
      zakenapi:
        enabled: true
        properties:
          url:
          client-id:
          secret: