spring:
  application:
    name: panorama

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security:
          web:
            authentication: INFO

panorama:
  config:
    authorization:
      clients:
        - client-id: app-all
          api-key: 49*HwbhRvxf!6vt7GnXj8xpmmZ87m9sK
          roles:
            - HAALCENTRAAL_BRP_GET_PERSOON
            - HAALCENTRAAL_BRP_GET_PERSONEN
            - ZAKEN_API_GET_ZAKEN
        - client-id: app-haalcentraal-only
          api-key: FCMzDjxA3Me8t6vTLLmD6VovbqmQaw@H
          roles:
            - HAALCENTRAAL_BRP_GET_PERSOON
            - HAALCENTRAAL_BRP_GET_PERSONEN
        - client-id: app-zaken-only
          api-key: iTwTRT@LBbdXyEAC.WfWCDvKimkKGTy2
          roles:
            - ZAKEN_API_GET_ZAKEN
    modules:
      haalcentraal-brp:
        enabled: true
        properties:
          api-url: http://localhost:5010/haalcentraal/api/
          api-key: ac045222c9e7cde8120b48735560f9b920bb58cd
      zakenapi:
        enabled: true
        properties:
          url: http://localhost:8001
          client-id: panorama
          secret: 7f9d2a8b1c4e0f5d3c8a9b7e1d7c9a2f